### PR TITLE
Expand test matrix w/ different django+cryptography releases

### PR DESCRIPTION
**Pull request by benjaoming**
## Summary

Changes tox to use current Python environment and sets Travis to test with Python 2.7, 3.4, 3.5, 3.6

### CODE REVIEW

**Comment by jamalex** [comment]
Ops, Travis didn't seem to like that! :crying_cat_face:

**Comment by benjaoming** [comment]
Currently fails because:

```
ERROR:   py27-django19-cryptography12: commands failed
  py27-django19-cryptography20: commands succeeded
```

Will disable `cryptography12` and open an issue to have it dealt with gracefully (doesn't mean you should support, but can perhaps do `CRYPTOGRAPHY_EXISTS = False` in case it's an unsupported version.

**Comment by benjaoming** [comment]
@jamalex @ralphiee22 this is ready for review now

Follow up:

https://github.com/learningequality/morango/issues/37
https://github.com/learningequality/morango/issues/38

**Comment by benjaoming** [comment]
There's a conflict now because `482fa8fcced824cd27f1943e47b096693bd270a6` specifies  `morango.settings` as the settings module.

1. Why is the settings module inside the application?
1. Why does it not even exist, anyways? :)

**Comment by benjaoming** [comment]
Reverted the change to `manage.py` from 180227ae7de97976d1b8e0dd8bac1d31d2e62702 to solve conflicts and rebased.

**Comment by benjaoming** [comment]
@jamalex @ralphiee22 I highly recommend that you get started with broadening version compatibilities and identifying incompatibilities by means of this PR :wink:

**Comment by benjaoming** [comment]
Okay, time is up guys :) This PR isn't complicated.

**Pull request merged**
